environment: prod-us

image:
  tag: 0.1.0

replicaCount: 1

ingress:
  enabled: true
  hosts:
    - host: datadog-demo-prod-us.demo.akuity.io
      paths:
        - path: /
          pathType: ImplementationSpecific

env:
  LAMBDA_URL: https://ovw5n62yxxr47xchmzfxqtd3sa0yfcay.lambda-url.us-west-2.on.aws/
