apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: apm-error-rate
  namespace: datadog-demo
spec:
  args:
  - name: service
  - name: env
  - name: version
  metrics:
  - count: 4
    failureCondition: default(result, 0) > 0
    failureLimit: 0
    interval: 15s
    name: error-rate
    provider:
      datadog:
        apiVersion: v2
        formula: errors / hits
        interval: 1m  # minimum 1m or else no metrics are returned
        queries:
          errors: sum:trace.http.request.errors{env:{{args.env}},service:{{args.service}},version:{{args.version}}}.as_rate()
          hits: sum:trace.http.request.hits{env:{{args.env}},service:{{args.service}},version:{{args.version}}}.as_rate()
