environment: prod-eu

image:
  tag: 0.2.0

replicaCount: 1

ingress:
  enabled: true
  hosts:
    - host: datadog-demo-prod-eu.demo.akuity.io
      paths:
        - path: /
          pathType: ImplementationSpecific

env:
  LAMBDA_URL: https://swmfgmz6nxsoxxov23dds3iys40dxpah.lambda-url.us-west-2.on.aws/
