environment: prod-eu

image:
  tag: 0.1.0

replicaCount: 1

ingress:
  enabled: true
  hosts:
    - host: datadog-demo-prod-eu.demo.akuity.io
      paths:
        - path: /
          pathType: ImplementationSpecific

env:
  LAMBDA_URL: https://evplpxotwcuolvscvv4ufe44zm0ewpje.lambda-url.us-west-2.on.aws/
