environment: dev

image:
  tag: 0.2.0

replicaCount: 1

ingress:
  enabled: true
  hosts:
    - host: datadog-demo-dev.demo.akuity.io
      paths:
        - path: /
          pathType: ImplementationSpecific

env:
  LAMBDA_URL: https://klecnctdhjoiiupvz2uiu4bkcm0miedm.lambda-url.us-west-2.on.aws/
