environment: dev

image:
  tag: 0.4.0

replicaCount: 1

ingress:
  enabled: true
  hosts:
    - host: datadog-demo-dev.demo.akuity.io
      paths:
        - path: /
          pathType: ImplementationSpecific

env:
  LAMBDA_URL: https://r2zx5t4yjpk7sn2hubanbjplyi0ecvhw.lambda-url.us-west-2.on.aws/
