env: staging

image:
  tag: v0.1.0

replicaCount: 1

ingress:
  enabled: true
  hosts:
    - host: kargo-demo-staging.demo.akuity.io
      paths:
        - path: /
          pathType: ImplementationSpecific
