environment: staging

image:
  tag: 0.2.0

replicaCount: 1

ingress:
  enabled: true
  hosts:
    - host: datadog-demo-staging.demo.akuity.io
      paths:
        - path: /
          pathType: ImplementationSpecific

env:
  LAMBDA_URL: https://rcpp4nv2yzkx2vy7mkj4fi4l3y0juaax.lambda-url.us-west-2.on.aws/
