environment: staging

image:
  tag: 0.2.0

replicaCount: 1

ingress:
  enabled: true
  hosts:
    - host: datadog-demo-staging.demo.akuity.io
      paths:
        - path: /
          pathType: ImplementationSpecific

env:
  LAMBDA_URL: https://svr6qmoqc2gca4a2dftwstg6jm0sdoqy.lambda-url.us-west-2.on.aws/
